build-job:
  image: node:alpine
  stage: build
  script:
    - npm install

test-job1:
  image: node:alpine
  services:
    - mongo
  stage: test
  before_script:
    - npm install
  script:
    - npm test