variables:
  MONGODB_URL: mongodb://mongodb:27017/task-k8s

build-job:
  image: node:alpine
  stage: build
  script:
    - npm install

test-job1:
  image: node:alpine
  services:
  - name: mongo
    alias: mongodb
  stage: test
  before_script:
    - npm install
  script:
    - npm test