version: "3.8"
services:
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  task-app:
    build: ./
    environment:
      MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/task-k8s?directConnection=true&authSource=admin
    ports:
      - 3000:3000
    depends_on:
      - mongodb
