version: "3.8"
services:
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  task-app:
    build: ./
    environment:
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: example
    ports:
      - 3000:3000
    depends_on:
      - mongodb
